### ISSUE TITLE
QR Codes not parsing on iOS

### ISSUE THREAD

**Issue by michaelharms6010** [hhanh00/zwallet#80]
### Subject of the issue
QR's are not scanning in mobile Ywallet
Stemming from issue reported here: https://github.com/michaelharms6010/zecpages/issues/118

### Your environment
Ywallet v1.3.6 
iOS v16.2

### Steps to reproduce
1. Go to https://zecpages.com/z/all
2.  Click "Create a post"
3. Enter some text
4. Try to scan the QR to the right

### Expected behaviour
A transaction should be prefilled in Ywallet with recipient address, amount, and memo

### Actual behaviour
The camera interface never goes away, presumably because the QR is not recognized. (Other QR readers on my phone recognize it instantly)

I get the same behavior (camera interface stays open, nothing seems to scan) with a QR that contains a simple zaddr.

Thank you!

**Comment by hhanh00** [comment]
From a quick look at the qr (I didn't try to scan) I think the issue is
with the border of the qr code.

I didn't write the qr code reader, it is coming from a popular c library.
If it works with some qr code but not others, it is probably an issue with
them...

**Comment by michaelharms6010** [comment]
I have been unable to make it work with **any** QR code, including the one generated by my desktop Ywallet.

**Comment by hhanh00** [comment]
Due to this related issue https://github.com/khoren93/flutter_zxing/issues/97 we may have to look for another open source qr code scanner

**Comment by pacu** [comment]
Hello! I came to report the same issue. 

Do we have any estimates on when there's going to be a fix? Can the change be outlined in a GitHub ticket for contributors to send PRs with fixes?

**Comment by zerodartz** [comment]
can confirm have same problem on iOS 16.5.1 ywallwet 1.3.6
no qr scan works

**Comment by TimUkrainian** [comment]
Hello, 

I confirm that QR code scan on YWallet to YWallet doesn't work. 

My IOS and YWallet are up to date.

**Comment by hhanh00** [comment]
For more context on this issue: Most barcode libraries use the [MLKit](https://developers.google.com/ml-kit) on Android to decode the image. Unfortunately, this is not acceptable for a fully open-source app since MLKit is Google proprietary code. At some point, I switched to a port of zxing to flutter but that library is not well maintained anymore because MLKit is usually preferred. 
Now we can either:
- wait for a fix in flutter zxing
- use the old barcode library just for iOS because the license does not affect iOS anyway
- fix it ourselves

**Comment by hhanh00** [comment]
Fixed in 1.4.5
